### ISSUE TITLE
Graphql Query Validation Error + Gatsby 404 error

### ISSUE THREAD

**Issue by AmaraWilliams** [EmpathyBytes/empathy-bytes-2024-2025#9]
**Summary**
These 2 errors seem to be related backend problems regarding 8 specific queries in files: about.js, project.js, article.js, and collection.js which is why this issue covers both errors (for now). For the graphql errors, they can be ignored by developers simply by closing the pop-up on development. However, there is now a noticeable load time for requesting related pages and for all the interview collection pages, a Gatsby 404 error will display. This Graphql handling error could be seen by users if we deploy as well, so this is a critical issue.

Reproduction of these errors are as follows:
 
**Graphql - Validation Error #85923**
Problem: Graphql is used to query the data in Drupal. For example, on the projects page there are buttons you can click that led you to the respective page and gather all related data for the page. Upon compilation, the terminal shows a "Failed - extract queries from components" and the Graphql errors.
![image](https://github.com/EmpathyBytes/empathy-bytes-2024/assets/32072685/e86f6758-320b-43d2-b3ac-c117769cfd43)

Reproduction:

1. [Follow steps on README for "Getting Started"](https://github.com/EmpathyBytes/empathy-bytes-2024/blob/master/README.md)
2. Upon `npm run develop`, error is shown in the terminal
![graphql-terminal](https://github.com/EmpathyBytes/empathy-bytes-2024/assets/32072685/fc1baaa5-1534-48d5-a326-c2dbf02db6e0)
3. To see the error on the webiste, simply go to [localhost:8000](http://localhost:8000/) or wherever the site is running if something is already running on that port.
![graphql-web](https://github.com/EmpathyBytes/empathy-bytes-2024/assets/32072685/adc037a1-495d-47d1-9a81-41ebd4cc49c0)

**Gatsby - 404 error**
Problem: This error appears for the interview collection. A static page was not created upon development which is why we are seeing a 404 error for the page. 

Reproduction:

1. [Follow steps on README for "Getting Started"](https://github.com/EmpathyBytes/empathy-bytes-2024/blob/master/README.md)
2. Click on the "Projects" page from the navbar
3. Select any collection of interviews to view
![gatsby404](https://github.com/EmpathyBytes/empathy-bytes-2024/assets/32072685/406049f8-bf31-4ee2-97a3-3866d4e9146f)

**Additional Related Problem: Time to fetch a page is noticeable**
Problem: 100% chance of reproduction can be seen when clicking on "Projects" and "About" in the navbar will prompt a "Preparing Requested Page" loading pop-up in the bottom lefthand side of the page. I believe this is caused by the queries as well if Graphql is overfetching somehow or just because of the main issue of the Graphql validation error.

Proposed Solution: Fixing the other issues may fix this one. We should priortize locating the schema.js file for these queries and take a closer look at our implementation of pages that use these queries.
Reproduction:
1. Select either page and view the bottom left of your screen
![page-loading](https://github.com/EmpathyBytes/empathy-bytes-2024/assets/32072685/4f794689-e1f9-4fe7-989a-b7aeacb861de)

**Comment by AmaraWilliams** [comment]
### **Misconfigured Gatsby-source-drupal plugin!** - 9/30
**Summary**
Upon doing npm run develop, I found this error referring to the plugin that links gatsby and drupal. It states that no nodes were found although we do have data on Drupal. I’m thinking our problem actually lies in Gatsby and is not specific to GraphQL. GraphQL is just a symptom of this plugin not working. Let’s all try to fix this plugin! I’ll update you on any steps as I go and please do the same if you agree this is the problem.

**Screenshots**

![gatsby-plugin](https://github.com/user-attachments/assets/00f59d20-c7a1-4ff0-92aa-893d193db2eb)

Useful links
[gatsby-source-drupal plugin](https://www.gatsbyjs.com/plugins/gatsby-source-drupal/)

**Comment by Twallace40** [comment]
While checking through Drupal, I was looking through the errors to see if there might be something there that could answer why Gatsby is failing to fetch from Drupal and found that “node access permissions” is disabled. It says we can rebuild permissions, but I did not want to pursue that further without first asking more experienced members if that would be wise
![Screenshot 2024-10-04 132037](https://github.com/user-attachments/assets/065c20f5-52bb-4826-8d69-bdb97feb76d0)

**Comment by AmaraWilliams** [comment]
This issue has been fixed through the amara-graphql-fix branch.

The issue was an outdated package.json and potentially a misconfigured gatsby.config file regarding the baseUrl. 

GraphQL unhandled errors described under **"Graphql - Validation Error #85923** do not pop up anymore and the link between Drupal > Gatsby > GraphQL is fixed. This also means the Gatsby 404 error is also resolved. We can now practice queries through the approprite link ([http://localhost:8000/___graphql](url)) upon development. 

GraphQL past: 
<img width="959" alt="image" src="https://github.com/user-attachments/assets/90f2eaa2-dad5-4d8a-b251-dd8aca9914c5">
As you can see, the scheme types are limited to just these on the left panel with no relations to our Drupal taxonomy terms 

GraphQL currently: 
![fixed-graphql](https://github.com/user-attachments/assets/552faaff-f3e6-4696-aeeb-5eb34bba86ca)

Gatsby 404 error resolved:
![gatsby-404error-fixed](https://github.com/user-attachments/assets/cb97abd3-720b-4e49-89c3-783fae8f4cd6)
